Leave-Queue-Item: true
Clear-Inventory-On-Queue: false
Teleport-To-End-When-Leaving-Queue: false
Fall-Damage-Enabled: false
Teleport-To-Lobby-On-Queue: true
Scoreboard-Enabled: true

Teleport-To-Start-If-Less-Than: 0
Points-To-Win: 5
Egg-Protection-Radius: 2

Time-Settings:
  Start-Countdown: 5
  Round-Starting-Countdown: 3
  Ending: 5
