Leave-Queue-Item: true
Clear-Inventory-On-Queue: false
Teleport-To-End-When-Leaving-Queue: false
Teleport-To-Start-If-Less-Than: 0
Teleport-To-Lobby-On-Queue: true

Time-Settings:
  Start-Countdown: 5
